import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.89.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

// HD Bank
const BANK_BIN = "970437";
const BANK_ACCOUNT = "0915966853";
const BANK_ACCOUNT_NAME = "NGUYEN HUU DUNG";
const QR_TEMPLATE = "compact2";

// Rate limit: max orders per IP per hour
const MAX_ORDERS_PER_HOUR = 5;
const rateLimitMap = new Map<string, { count: number; resetAt: number }>();

interface CreateOrderRequest {
  package_id: string;
  /** Optional contact captured at order creation so admin can follow up
   * when SePay webhook fails to auto-verify the transaction. */
  customer_contact?: string;
  customer_contact_method?: "zalo" | "discord" | "email" | "phone";
}

const VALID_CONTACT_METHODS = new Set(["zalo", "discord", "email", "phone"]);

function getClientIp(req: Request): string {
  return (
    req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    req.headers.get("cf-connecting-ip") ||
    "unknown"
  );
}

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const entry = rateLimitMap.get(ip);

  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + 3600_000 });
    return true;
  }

  if (entry.count >= MAX_ORDERS_PER_HOUR) {
    return false;
  }

  entry.count++;
  return true;
}

function buildVietQrUrl(amount: number, paymentCode: string): string {
  const addInfo = encodeURIComponent(`ROK ${paymentCode}`);
  const accountName = encodeURIComponent(BANK_ACCOUNT_NAME);
  return `https://img.vietqr.io/image/${BANK_BIN}-${BANK_ACCOUNT}-${QR_TEMPLATE}.png?amount=${amount}&addInfo=${addInfo}&accountName=${accountName}`;
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const ip = getClientIp(req);

    // Rate limit
    if (!checkRateLimit(ip)) {
      return new Response(
        JSON.stringify({ error: "Too many orders. Try again later." }),
        {
          status: 429,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Parse body
    const body: CreateOrderRequest = await req.json();

    if (!body.package_id) {
      return new Response(
        JSON.stringify({ error: "Missing package_id" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Validate contact method if provided
    if (body.customer_contact_method && !VALID_CONTACT_METHODS.has(body.customer_contact_method)) {
      return new Response(
        JSON.stringify({ error: "Invalid customer_contact_method" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Trim + length-limit contact (prevent abuse)
    const contact = body.customer_contact?.trim().slice(0, 200) || null;
    const contactMethod = body.customer_contact_method || null;

    // Supabase admin client (service_role_key bypasses RLS)
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // Validate package exists + active + in stock
    const { data: pkg, error: pkgError } = await supabaseAdmin
      .from("service_packages")
      .select("id, price, is_active, name, stock, sold_count")
      .eq("id", body.package_id)
      .single();

    if (pkgError || !pkg || !pkg.is_active) {
      return new Response(
        JSON.stringify({ error: "Package not found or inactive" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Check stock (null = unlimited)
    if (pkg.stock !== null && pkg.sold_count >= pkg.stock) {
      return new Response(
        JSON.stringify({ error: "Out of stock" }),
        {
          status: 400,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Create order (payment_code auto-generated by DB trigger)
    const { data: order, error: orderError } = await supabaseAdmin
      .from("orders")
      .insert({
        user_id: null,
        package_id: body.package_id,
        total_amount: pkg.price,
        status: "pending",
        customer_contact: contact,
        customer_contact_method: contactMethod,
      })
      .select("id, payment_code")
      .single();

    if (orderError || !order) {
      console.error("Order creation failed:", orderError);
      return new Response(
        JSON.stringify({ error: "Failed to create order" }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    // Create payment record
    await supabaseAdmin.from("payments").insert({
      order_id: order.id,
      amount: pkg.price,
      method: "bank_transfer",
      status: "pending",
    });

    // Increment sold_count
    if (pkg.stock !== null) {
      await supabaseAdmin
        .from("service_packages")
        .update({ sold_count: pkg.sold_count + 1 })
        .eq("id", pkg.id);
    }

    // Build VietQR URL
    const qrUrl = buildVietQrUrl(pkg.price, order.payment_code);

    return new Response(
      JSON.stringify({
        order_id: order.id,
        payment_code: order.payment_code,
        qr_url: qrUrl,
        amount: pkg.price,
        package_name: pkg.name,
      }),
      {
        status: 201,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error("Error in create-order:", message);
    return new Response(
      JSON.stringify({ error: message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
});
